on:
  push:
    branches:
    - master
    paths:
    - 'thrift/**'

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-typescript-package:
    needs: bump-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: install
      run: npm install
    - name: generate and publish
      run: ./gen-typescript.sh
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  generate-swift-package:
    needs: bump-tag
    runs-on: ubuntu-latest
    steps:
      uses: guardian/generate-native-package@master
      with:
        platform: 'ios'
