on:
  push:
    branches:
    - master
    paths:
    - 'thrift/**'
  
jobs:
  generate-typescript-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
    - name: generate and publish
      run: ./gen-typescript.sh
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}